#import "@local/probonotes:0.2.1": *
#show: style.with(
  // Title and subtitle
  course-name: "Abstract Algebra",
  course-code: "SF1678",
  author: "",
  date: none,
  title-size: 30pt,
  subtitle-size: 16pt,
  title-space: 0em,

  // Layout
  size: 12pt,
  margin: 0.5cm, // 0.5cm for computer, 0.1cm for phone.
  width: 14cm, // 14-16cm for computer, 8cm for phone.
  height: auto,
  end-space: 40em, // 40em to cover computer screen.
  heading-break: false,

  // Content
  language: "en", // sv for Swedish.
  contents: true,
  memes: true,
)

#image("assets/image.png")

#image("assets/image-3.png")

#image("assets/image-4.png")

#image("assets/image-5.png")

2.4 exercises

#image("assets/image-6.png")

#image("/assets/image.png")

find a cyclic infinite group

find an infinite subset that is closed under operation but not inverse

#theorem[
  If $p$ is the smallest prime index of $G$,
  then all subgroups of order $p$ are normal.
]

#theorem[Cauchy's or Prime Divisors][
  If $p$ is a prime that divides $|G|$,
  then $G$ must have a subgroup _and an element_ of order $p$.
]

#theorem[Sylow's or Prime Power Divisors][
  If $p^k$ is prime _power_ and divides $|G|$,
  then $G$ must have a subgroup of order $p^k$.
]

#definition[$p$-group][
  Let $G$ be a group,
  let $p$ be a prime,
  let $alpha$ be a positive integer, and
  let $m$ be a positive integer such that $m divides.not alpha$.
  + If $|G| = p^alpha$ for some $alpha >= 1$,
    then $G$ is a *$p$-group* and its subgroups
    are *$p$-subgroups*.
  + If $|G| = p^alpha m$,
    then the $n_p (G)$ subgroups $"Syl"_p (G)$ of order $p^alpha$
    are *Sylow $p$-subgroups*.
]

#lemma[
  Let $P in "Syl"_p (G)$. If $Q$ is a $p$-subgroup of $G$,
  then $ Q inter N_G (P) = Q inter P. $
]

#theorem[Sylow's][
  Let $G$ be a group of order $p^alpha m$.
  + $"Syl"_p (G) != emptyset$
  + If $P$ is a Sylow $p$-subgroup and $Q$ is a $p$-subgroup,
    then $ exists g in G : Q <= g P g^(-1), $
    i.e., $Q$ is contained in some conjugate of $P$.
    In particular, any two Sylow $p$-subgroups of $G$ are conjugate in $G$.
  + $n_p equiv 1 space (mod p)$.
  + $n_p = lr([G : N_G (P)])$ for every $P in "Syl"_p (G)$.
]

#corollary[
  Let $P <= G$ be a Sylow $p$-subgroup.
  Then the following are equivalent:
  + $P$ is the only Sylow $p$-subgroup of $G$, i.e., $n_p (G) = 1$
  + $P$ is normal in $G$
  + $P$ is characteristic in $G$
  + All subgroups generated by elements of $p$-power order are $p$-groups,
    i.e., if $X$ is any subset of $G$ such that $|x|$ is a power of $p$
    for all $x in X$, then $chevrons(X)$ is a $p$-group.
]

= Sets

== Relations

=== Set Theory

#definition[Tuple][
  A tuple (or sometimes *list*) is
  a finite, ordered collection of elements,
  possibly with repetitions.

  An $n$-tuple is of length $n$.
  A $2$-tuple is called an *ordered pair*.
]

=== Morphisms

#definition[Map][
  Subsets of the Cartesian product $A times B$ are called *relations*.
  A *map* is a *well-defined* relation written
  $
    f subset.eq A times B
    quad "or" quad
    f : A -> B
    quad "or" quad
    A ->^f B
  $
  and is
  - *surjective* or *onto*
    if $f(A) = B$,
    which is equivalent to being *right invertible*
    with $f compose f^(-1) = id_B$.
  - *injective* or *one-to-one*
    if $a_1 != a_2 ==> f(a_1) != f(a_2)$,
    which is equivalent to being *left invertible*
    with $f^(-1) compose f = id_A$.
  - *bijective* or a *one-to-one correspondence*
    if both above apply,
    which is equivalent to being *invertible*.
]

#definition[Homomorphism][
  A *homomorphism* is a map between algebraic structures
  that preserves the structure.

  A group homomorphism $phi : G -> H$ satisfies
  $ phi(g * gamma) = phi(g) dot phi(gamma) $
  for all $g, gamma in G$.
]

#theorem[
  If $phi : G -> H$ is a group homomorphism,
  + $phi(id_G) = id_H$
  + $phi(g^(-1)) = phi(g)^(-1)$ for all $g in G$
  + $phi(G) <= H$
]

#definition[Isomorphism][
  An *isomorphism* is a bijective homomorphism.

  If there exists an isomorphism between two algebraic structures,
  they are said to be *isomorphic*, denoted with $tilde.equiv$.
]

#definition[Endomorphism][
  An *endomorphism* is a homomorphism from a mathematical object to itself.
]

#definition[Automorphism][
  An *automorphism* is simultaneously an isomorphism and an endomorphism:
  a bijective homomorphism from an object to itself.
]

#example[
  The *identity map* $id_X$ is a trivial automorphism defined
  $ id_X (x) = x wide forall x in X. $
]

#example[
  An automorphism of a set is called a *permutation*.
]

=== Equivalance

#definition[Equivalance Relation][
  An *equivalance relation* on a set $A$
  is a relation $R subset.eq A times A$
  with the following properties:
  + / reflexive: $(a, a) in R wide forall a in A$
  + / symmetric: $(a, b) in R ==> (b, a) in R$
  + / transitive: $(a, b), (b, c) in R ==> (a, c) in R$

  If $(x, y) in R$ we write $x R y$ or $x tilde y$.
]

Let $R$ be an equivalence relation on a set $A$.

#definition[Equivalence Class][
  The *equivalence class* of an element $a in A$
  $ [a] = dash(a) = {b in A mid(|) b tilde a} $
  is the set of all elements related to it.
]

#example[
  The modulo $m$ congruence class $[a] = {a + k m mid(|) k in ZZ}.$
]

#definition[Quotient Set][
  The *quotient set* of $A$ by $R$
  $ A slash R = {[a] mid(|) a in A} $
  is the set of all equivalence classes induced by the relation.
]

#definition[Partition][
  A *partition* $cal(P)$ of a set $A$
  is a collection of non-empty, disjoint subsets of $A$
  whose union is $A$.
]

#theorem[
  The quotient set $A slash R$ forms a partition of $A$.
]

#definition[Quotient Map][
  A *quotient map* is a map $pi : A -> A slash R$ defined by
  $ pi(a) = [a]. $
]

#theorem[][
  Quotient maps are surjective.
]

== $ZZ$

=== Linear Diophantine Equations

Let $a$ and $b$ be integers with $gcd(a, b) = d$.

#lemma[Bézout's Identity][
  There exist integers $x$ and $y$ such that $a x + b y = d$.
]

#lemma[Euclid's][
  If $p$ is prime and $p divides a b$, then $p divides a$ or $p divides b$.
]

#theorem[Solvability Condition][
  The linear Diophantine equation $a x + b y = c$ has (infinitely many)
  solutions if and only if $d divides c.$
]

#theorem[Solutions][
  The solutions, if they exist, are
  $ x = x_0 + t b / d, quad y = y_0 - t a / d, quad "for" t in ZZ. $
]

#theorem[Euclidean Algorithm][
  Let $a$ and $b$ be non-negative integers with $a >= b$.
  Then there exist unique integers $q$ and $r$ such that
  $ a = q b + r, quad 0 <= r < b. $
]

#example[
  We apply the algorithm to compute $gcd(252, 105)$:
  $
    252 & = 2 dot 105 + 42 \
    105 & = 2 dot 42 + 21 \
     42 & = 2 dot 21 + 0 \
  $
  Hence, $gcd(252, 105) = 21$.
]

#example[
  We then use our results to solve $252 x + 105 y = 21$.

  Since $gcd(252, 105) = 21$, we now work backwards:
  $
    21 & = 105 - 2 dot 42 \
       & = 105 - 2 dot (252 - 2 dot 105) \
       & = 105 - 2 dot 252 + 4 dot 105 \
       & = 5 dot 105 - 2 dot 252 \
       & = -2 dot 252 + 5 dot 105
  $
  So a particular solution is $x_0 = -2, y_0 = 5$.
  The general solutions are
  $ x = -2 + 5t, quad y = 5 - 12t, quad "for" t in ZZ. $
]

= Groups

== Definitions

=== Groups

#definition[Group][
  A *group* $(G, *)$ is a nonempty set $G$ with a binary operation
  $ * : G times G -> G $
  such that for all $a, b, c in G$, it satisfies
  1. (Closure) $a * b in G$
  2. (Associativity) $(a * b) * c = a * (b * c)$
  3. (Identity) $exists e in G : e * a = a * e = a$
  4. (Inverse) $exists a^(-1) in G : a * a^(-1) = a^(-1) * a = e$

  Additionally, a group is called *abelian* or *commutative* if it is
  5. (Commutative) $a * b = b * a$
]

#examples[
  The *general linear group* $G L_n (RR)$
  consists of all matrices in $RR^(n times n)$ with $det != 0$.
  The *special linear group* $S L_n (RR)$
  additionally requires that $det = 1$.
]

#tip[
  The proof of (iii) and (iv) can be shortened if (v) is proven.
]

#note[
  Defying conventional wisdom,
  *abelian* is usually not capitalized.
]

=== Subgroups

Let $(G, *)$ be a group.

#definition[Subgroup][
  A subset $H subset.eq G$ is a *subgroup* if it is itself a group
  under the operation inherited from $G$.
]

#theorem[Subgroup Criterion][
  A subset $H subset.eq G$ is a subgroup if and only if
  1. $H != emptyset$ (nonempty)
  and
  2. $a * b^(-1) in H quad forall a, b in H$
  or
  2. $a * b in H quad forall a, b in H$
  + $a^(-1) in H quad forall a in H$
  or
  2. $a * b in H quad forall a, b in H$ (closed)
  + $|H| < oo$ (finite)
]

=== Cyclic

#definition[Cyclic Subgroup][
  For every $a in G$, the set
  $ ⟨a⟩ = {a^k mid(|) k in ZZ} $
  forms a *cyclic subgroup* of $G$.
]

#theorem[
  The cyclic subgroup $⟨a⟩ <= G$ is
  the smallest subgroup containing $a.$ 
]

#definition[Generating Set][
  The subgroup
  $⟨S⟩ = ⟨s, s^(-1) mid(|) s in S⟩ = {s^k mid(|) s in S, k in NN}$
  consists of all _finite_ products of elements
  in its *generating set* $S$ and their inverses.
]

#definition[Generator][
  An element $a in G$ is a *generator* of $G$ if $⟨a⟩ = G$.
]

#definition[Cyclic Group][
  We say $G$ is a *cyclic group* if it contains a *generator* of itself.
]

#theorem[
  All subgroups of a cyclic group are cyclic.
]

#theorem[
  Every cyclic group is abelian.
]

#proof[
  Let $g$ and $gamma$ be elements of a cyclic group $G = ⟨a⟩$.
  Then there are integers $m$ and $n$ such that $g = a^m$ and $y = a^n$, so
  $ g gamma = a^m a^n = a^(m + n) = a^(n + m) = a^n a^m = gamma g. $
]

== $ZZ_n$

Let $a$ and $n$ be positive integers and let $p$ be prime.

#definition[$ZZ_n$][
  The *integers modulo $n$* is a set of congruence classes
  $ ZZ_n = {[0], [1], ..., [n - 1]} $
  that form an abelian group under $+$ and a monoid under $times$,
  together forming a ring with a group of units called
  the *multiplicative group of integers modulo $n$*, denoted $U(n)$
  and consisting of the integers coprime to $n$,
  with inverse elements defined to satisfy
  $a a^(-1) (equiv a^(-1) a) equiv 1 space (mod n).$
]

#definition[Euler's Totient Function][
  $
    phi.alt (n)
    = |U(n)|
    = |{k in ZZ mid(|) 1 <= k <= n "and" gcd(n, k) = 1}|
  $
]

#example[
  $phi.alt (12) = |{1, 5, 7, 11}| = 4$
]

#theorem[Euler's][
  If $a$ and $n$ are coprime, then
  $ a^(phi.alt(n)) equiv 1 quad (mod n). $
]

#proof[
  The order of $a$ is $|U(n)| = phi.alt (n).$
]

#lemma[
  $phi.alt(p) = p - 1$
]

#theorem[Fermat's Little][
  If $a$ and $p$ are coprime, then
  $ a^(p - 1) equiv 1 quad (mod p). $

  In general, even if they are not coprime,
  $ a^p equiv a quad (mod p). $
]

== Families

=== Commutation

Let $X$ be any nonempty subset of $G$.

#definition[Centralizer][
  The *centralizer* of $X$ in $G$ is the set
  $ C_G (X) = {g in G mid(|) g x g^(-1) = x "for all" x in X}, $
  all elements in $G$ that commute with all elements in $X$,
  fixing every element of $X$ under conjugation.
]

#remark[
  $g x g^(-1) = x <==> g x = x g$
]

#note[
  If $X$ is a singleton set ${x}$, we simply write $C_G (x)$.
]

#definition[Center][
  The *center* of $G$ is the set
  $
    Z(G) = C_G (G) =
    {g in G mid(|) g gamma g^(-1) = gamma "for all" gamma in G},
  $
  all elements in $G$ that commute with all elements in $G$,
  fixing every element of $G$ under conjugation.
]

#definition[Normalizer][
  The *normalizer* of $X$ in $G$ is the set
  $ N_G (X) = {g in G mid(|) g X g^(-1) = X}, $
  all elements in $G$ that commute with $X$ as a set,
  fixing $X$ as a set under conjugation.
]

#theorem[
  $Z(G) <= C_G (X) <= N_G (X) <= G,$
  with all equalities if $G$ is abelian.
]

#theorem[
  If $X$ is a subgroup, not just a subset, then $X <= N_G (X) <= G.$
]

#definition[Commutator][
  Let $G$ be a group with elements $x, y in G$
  and nonempty subsets $A, B subset.eq G$.
  + The *commutator* of $x$ and $y$ is $[x, y] = x^(-1) y^(-1) x y.$
  + $[A, B] = chevron.l [a, b] mid(|) a in A, b in B chevron.r$
  + Define $G' = chevron.l [x, y] mid(|) x, y in G chevron.r$,
    the subgroup of $G$ generated by commutators of elements from $G$,
    called the *commutator subgroup* of $G$.
]

#theorem[
  $[x, y] = id_G <==> x "and" y "commute"$
]

=== Group Action

#definition[Group Action][
  A map $dot : G times X -> X$ is a *(left) group action* if it satisfies:
  + (Identity)
    $e dot x = x$
    for all $x in X$.
  + (Compatibility)
    $g dot (h dot x) = (g h) dot x$
    for all $g, h in G$ and $x in X$.
]

Let $dot : G times X -> X$ be a group action.

#definition[Orbit][
  The *orbit* of $x in X$ is the set
  $ G dot x = {g dot x mid(|) g in G}, $
  all points in $X$ that $x$ can be moved to by the group action.
]

#definition[Transitive][
  The action of $G$ on $X$ is *transitive* if there is only one orbit, i.e.,
  given any pair $x, y in X$ there is some $g in G$ such that $g dot x = y$.
]

#theorem[
  The orbits of a cyclic subgroup $⟨sigma⟩ <= S_n$ is
  the sets of numbers in the distinct cycles
  given by its cycle decomposition.
]

#example[
  The orbits of $⟨cycle(1, 2) cycle(3, 4, 5)⟩$ are ${1, 2}$ and ${3, 4, 5}$.
]

#definition[Stabilizer][
  The *stabilizer* of $x in X$ is the set
  $ G_x = {g in G mid(|) g dot x = x}, $
  all elements in $G$ that fix $x$ under the group action.
]

#theorem[
  $|G dot x| = [G : G_x] = |G| / |G_x|$
]

#definition[Fixed Point Set][
  The *fixed point set* of $g in G$ is the set
  $ X^g = {x in X mid(|) g dot x = x}, $
  all elements in $X$ that are fixed under $g$.
]

#definition[Kernel][
  The *kernel* is the set
  $ ker(dot) = {g in G mid(|) g dot x = x "for all" x in X}, $
  all elements in $G$ that fix every element of $X$ under the group action.
]

#definition[Faithful][
  A group action is *faithful* if $ker(dot) = {e}$.
]

== Cosets

=== Left and Right

Let $H$ be a subgroup of a group $G$.

#definition[Coset][
  For any $g in G$, the *left coset* of $H$ in $G$ is
  $ g H = {g * h mid(|) h in H}. $

  Similarly, the *right coset* is
  $ H g = {h * g mid(|) h in H}. $

  An element of a coset is a *representative* for that coset.
]

#theorem[
  The left and right cosets respectively partition $G$.
]

#theorem[
  There are equally many left and right cosets of $H$ in $G$.
]

=== Order

#definition[Order][
  The *order of a group* $|G|$ is the number of elements in $G$.

  The *order of an element* $|g|$ is the smallest positive integer $n$
  such that $g^n = e$. If there is no such $n$, the order is infinite.
]

#theorem[Classification][
  #context {
    let (Z, Zn) = match-widths($ZZ$, $ZZ_n$)
    let (eq, lt) = match-widths($=$, $<$)

    [
      If $G$ is a cyclic group of order $n$, then
      + $G tilde.equiv #Z <==> n #eq oo$
      + $G tilde.equiv #Zn <==> n #lt oo$
    ]
  }
]

#definition[Direct Product][
  The *direct product* $G_1 times G_2 times dots.h.c times G_n$
  of the sets $G_1, G_2, ..., G_n$ with the operations $*_1, *_2, ..., *_n$
  is the set of $n$-tuples with operation defined componentwise:
  $
    (g_1, ..., g_n) * (gamma_1, ..., gamma_n)
    = (g_1 *_1 gamma_1, ..., g_n *_n gamma_n).
  $

  If there are infinitely many groups,
  the $n$-tuples are replaced by sequences.
]

#theorem[
  $
    G slash G_i tilde.equiv
    G_1 times dots.h.c times G_(i-1) times G_(i+1) times dots.h.c times G_n
  $
]

#theorem[
  $ |G_1 times G_2 times dots.h.c times G_n| = |G_1| |G_2| dots.h.c |G_n| $
]

#theorem[
  Let $x_i = (id_1, ..., id_(i-1), g_i, id_(i+1), ..., n)$
  for some $g_i in G_i$. Then
  $
    |x_1 x_2 dots.h.c x_n| =
    lcm(|x_1|, |x_2|, ..., |x_n|).
  $
]

#lemma[
  Let 
]

#theorem[
  Let $m, n in ZZ^+$.
  Then $ZZ_m times ZZ_n tilde.equiv ZZ_(m n) <==> gcd(m, n) = 1.$
]

#proof[
  We must prove both implications.

  Consider the element $g = (1, 1) in ZZ_m times ZZ_n$
  which has order $|g| = lcm(|1_m|, |1_n|) = lcm(m, n)$.

  First assume $gcd(m , n) = 1$.
  Then $|g| = m n$

]

#definition[Bounded Group][
  $exists N in ZZ^+ : g^N = e space forall g in G$
]

#definition[Torsion Group][
  $forall g in G space exists n in ZZ^+ : g^n = e$
]

#examples[
  Finite groups. Bounded groups.
]

#definition[Torsion Subgroup][
  If $G$ is abelian, its torsion subgroup is an abelian subgroup
  $ T(G)
  = {g in G : exists n in ZZ^+ : g^n = e}
  = {g in G : |g| < oo}. $

  Two special cases arise:
  + If $T(G) = G$ then $G$ is a *torsion abelian group*.
  + If $T(G) = {e}$ then $G$ is a *torsion-free abelian group*.
]

#definition[Index][
  The *index* of $H$ in $G$ is the number of left cosets, denoted
  $[G : H].$
]

#theorem[Lagrange's][
  Let $G$ be finite.
  Then the order of $H$ divides the order of $G$.
]

#corollary[
  If $G$ is of prime order, it
  + lacks proper nontrivial subgroups
  + is generated by any element $g != e$
  + is cyclic
]

#theorem[Lagrange's, Generalized][
  Regardless of whether G is finite or infinite,
  $ |G| = [G : H] |H|. $
]

#proof[
  $G$ has $|G|$ elements and is partitioned into
  $[G : H]$ distinct left cosets, each of which has $|H|$ elements.
]

#corollary[
  If $H normal.eq G$ then $[G : H] = |G| / |H| = |G slash H|.$
]


#theorem[
  Let $(g, h) in G times H$ be a tuple of groups.
  If they have finite orders $|g| = r < oo$ and $|h| = s < oo$,
  then $|(g, h)| = lcm(r, s)$.
]

#corollary[
  $ZZ_m times ZZ_n tilde.equiv ZZ_(m n) space <==> space gcd(m, n) = 1$
]

=== Conjugation

#definition[Conjugation][
  The *conjugation* by $a in G$ is an *inner automorphism* of $G$
  defined $g mapsto g a g^(-1)$.
]

#definition[Normal Subgroup][
  #let dist = v(1em)
  
  The following are equivalent for a subgroup $H$ of $G$:
  + $H$ is a *normal subgroup* of $G$,
    denoted $H normal.eq G$.
    #dist
  + $g h g^(-1) in H$ for all $g in G$ and $h in H$.
  + $g H g^(-1) subset.eq H$ for all $g in G$.
  + $g H g^(-1) = H$ for all $g in G$.
    #dist
  + $g H = H g$ (equal left coset and right coset) for all $g in G$.
  + The sets of left and right cosets coincide.
]

#examples[
  Trivially, $G normal.eq G$ and ${e} normal.eq G$.
]

#warning[
  Normalness is not transitive, i.e.,
  $
    A normal.eq B normal.eq C
    space cancel(arrow.r.double.long, length: #50%, angle: #20deg) space
    A normal.eq C.
  $
]

#note[
  Some authors use $normal$ exclusively for proper normal subgroups,
  while others use it for all normal subgroups.
  
  The same principle holds for the subset sign $subset$.
]

#theorem[
  Every subgroup of index $2$ is normal.
] <thm-index2>

#proof[
  Let $H <= G$ be the subgroup such that $[G : H] = 2$.
  We wish to show that $g H = H g$ for all $g in G$.

  If $g in H$, then $g H = H = H g$.
  Otherwise, if $g in.not H$, then $g H = G slash H = H g$
  since $H union H g = G = H union g H$. // Not obvious!
  
  Thus, $g H = H g$ for all $g$, so $H$ is a normal subgroup of $G$.
]

#definition[Simple Group][
  A group is *simple* if it has no normal nontrivial proper subgroup.
]

#theorem[
  All subgroups of abelian groups are normal subgroups.
]

#definition[Fiber][
  Let $phi : G -> Omega$ be a surjective map from a group to a set.
  The *fiber* of $phi$ over some $omega in Omega$ is its preimage in $G$
  $ phi^(-1) (y) = {g in G mid(|) phi.alt(g) = omega}, $
  the set of all elements in the domain that map to $omega$.
]

Let $phi : G -> H$ be a group homomorphism.

#definition[Fiber of Group][
  The *fiber* of $phi$ over some $h in H$ is
  $ phi^(-1)(h) = {g in G mid(|) phi(g) = h}. $
]

#theorem[
  The collection of nonempty fibers forms a partition of $G$.
  Hence, every $g in G$ is only in the fiber over $phi(g)$.
]

#definition[Kernel][
  The *kernel* of a group homorphism $phi$ is the set
  $ ker phi = phi^(-1)(id_H) = {g in G mid(|) phi(g) = id_H }. $
]

Let $K = ker phi$.

#theorem[
  $K normal.eq G$
]

#theorem[
  For every $g in G$ such that $phi(g) = h$ the entire fiber is
  $ phi^(-1)(h) = g K = K g. $
  
  In words, the fibers of a homomorphism are the cosets of its kernel.
]

#definition[Quotient Group, Alternative][
  The quotient group is
  $ G slash K = {phi^(-1)(h) mid(|) h in phi(G)}, $
  the set of all nonempty fibers of $phi$.

  If $phi$ is surjective, then $phi(G) = H$ and all fibers are nonempty.
]

#definition[Quotient Group][
  Let $N normal.eq G$.
  The *quotient group* or *factor group* is
  $ G slash N = {g N mid(|) g in G} (= {N g mid(|) g in G}), $
  the set of all left cosets of $N$ in $G$,
  paired with the group operation
  $ (a N) * (b N) = (a b) N quad forall a, b in G, $
  which is well-defined if and only if $N normal.eq G$.
]

#example[#align(center)[
  #let headings = ("name", "symbol", "set", "operation")

  #let names = ("large group", "normal subgroup", "quotient group")
  #let syms = ($G$, $N$, $G slash N$)
  #let sets = ($ZZ$, $n ZZ$, $ZZ_n$)
  #let ops = ($+$, $+$, $+ mod n$)

  #let contents = names.zip(syms, sets, ops)
  
  #table(
    columns: 4,
    stroke: none,
    align: (right, left, left, left),
    inset: (x: 6pt, y: 7pt),
    
    table.vline(x: 1, stroke: 0.5pt),
    table.hline(y: 1, stroke: 0.5pt),

    table.header(..headings),
    ..contents.flatten(),
  )
]]

#definition[Natural Projection][
  Let $N normal.eq G$.
  The natural/canonical projection/homomorphism
  is the map $pi : G -> G slash N$ defined by $pi(g) = g N$ for all $g in G$.
]

#theorem[
  For $pi$ defined above:
  + $pi$ is a homomorphism
  + $pi$ is surjective, i.e., $pi(G) = G slash N$
  + $ker pi = N$
]

=== The Isomorphism Theorems

Let $phi : G -> H$ be a group homomorphism.

#theorem[First or Fundamental of Homomorphisms][
  + $ker phi normal.eq G$
  + $phi(G) tilde.equiv G slash ker phi$
  + $phi(G) <= H$
]

#corollary[
  #let dist = v(0.5em)

  + $|phi(G)| = [G : ker phi]$
    #dist
    The following are equivalent:
  + $phi "is surjective"$
  + $H tilde.equiv G slash ker phi$
  + $|G| = [G : ker phi] quad$ #proof[See (i).]
    #dist
    The following are equivalent:
  + $phi "is injective"$
  + $ker phi = id_G$
]

#lemma[
  If $A$ and $B$ are subgroups of $G$, then
  $ A B <= G <==> A B = B A $

  Furthermore, if $A$ and $B$ are finite, then
  $ |A B| = (|A\||B|)/(|A inter B|). $
]

#theorem[Second or Diamond or Parallelogram][
  Let $S <= G$ and $N <= G$ be subgroups such that $S <= N_G (N)$. Then,
  + $S N <= G$ #h(1em) #proof[See the above lemma.] 
  + $N normal.eq S N$
  + $S inter N normal.eq S$
  + $(S N) slash N tilde.equiv S slash (S inter N)$
]

#image("assets/image-1.png", width: (72 / 300) * 333pt)

== Permutations

=== Transpositions

#definition[Transposition][
  A *transposition* of the elements $i, j in {1, ..., n}$
  is the permutation $tau_(i j)$ with the cycle notation $(i space j)$.
]

#theorem[
  Any permutation can be written as compositions of transpositions.
]

#theorem[
  The identity permutation may only be written as
  an even number of transpositions.
]

#theorem[Order][
  $|sigma| = "length"(sigma)$
]

#definition[Sign of a Permutation][
  Let $k$ be the number of transpositions in
  any decomposition of a $(k + 1)$-cycle $sigma in S_n$,
  The *sign* of $sigma$ is $(-1)^k$.

  #context {
    let (even, odd) = match-widths([*even*], [*odd*])

    [
      Hence,
      + if $k$ is #even then $sgn(sigma) = +1$
        and $sigma$ is said to be even.
      + if $k$ is #odd then $sgn(sigma) = -1$
        and $sigma$ is said to be odd.
    ]
  }
]

#theorem[Permutation Inverse][
  Let $sigma in S_n$ be a permutation.
  + $sigma = cycle(a_1, a_2, dots.h.c, a_m) = tau_1 tau_2 dots.h.c tau_k$
    for some $m <= n$ and $k$
  + $sigma^(-1)$ exists
  
    #proof[
      $sigma$ is a bijection.
    ]
  + $sigma^(-1) = cycle(a_m, dots.h.c, a_2, a_1) = tau_1 tau_2 dots.h.c tau_k$

    #proof[
      Consider that
      $(tau_i tau_j)^(-1) = tau_j^(-1) tau_i^(-1) = tau_j tau_i$
      and
      $cycle(a, b, c)^(-1) = (a -> b -> c -> a)^(-1) = (a <- b <- c <- a)$.
    ]
  + $sigma^(-1) = sigma^k <==> "length"(sigma) = k$

    #proof[
      The order of a $k$-cycle is $k$.
    ]
  + $sgn(sigma^(-1)) = sgn(sigma) = (-1)^k$
]

#definition[Fixed Point)][
  A *fixed point* is invariant under
  a transformation such as a permutation.
]

=== Symmetric Groups

#definition[Symmetric Group][
  The *symmetric group* of the finite set $X = {1, 2, ..., n}$ is
  $ S_n = {sigma : X -> X mid(|) sigma "is bijective"} $
  and consists of $n!$ permutations,
  which form *the symmetric group on $n$ letters*
  under the operation of composition
]

#theorem[
  The automorphism group of a set is its symmetric group.
]

#definition[Permutation Group][
  A subgroup of a symmetric group $S_n$ is a *permutation group*.
]

#definition[Alternating Group][
  The *alternating group*
  $ A_n = {sigma in S_n mid(|) "sgn"(sigma) = 1} $
  is the subgroup of $S_n$ consisting of all even permutations.

  It has $n!/2$ elements for $n >= 2$.
]

#theorem[
  The number of $k$-cycles is
  $ choose(n, k) (k - 1)! = n!/((n-k)!k!) (k - 1)! = n!/((n-k)!k) $
  in $S_n$.
  In $A_n$ there are equally many if $k$ is odd,
  but $0$ if $k$ is even.
]

#problem[
  Show that $A_4$ has no subgroup of order $6$.
]

#solution[
  Assume the opposite;
  suppose there is a subgroup $H <= A_4$ such that $|H| = 6$.

  By Lagrange's theorem,
  $[A_4 : H] = |A_4| / |H| = 12 / 6 = 2.$
  @thm-index2 dictates that any subgroup of index $2$ is normal,
  so $H normal A_4$.
  Since the quotient group has order $|A_4 slash H| = [A_4 : H] = 2$,
  $ (g H)^2 = H space ==> space g^2 H = H space ==> space g^2 in H $
  for all $g in A_4$.

  There are 8 distinct 3-cycles in $A_4$.
  The inverse of any 3-cycle $g in A_4$ is
  $g^(-1) = g^2 in H$, since the length is 3.
  Hence, $g in H$.
  However, there are 8 distinct 3-cycles in $A_4$,
  so it follows that $|H| >= 8 > 6$.
]

#theorem[
  The sign map $"sgn" : S_n -> {1, -1}$ is a group homomorphism.

  The kernel of this homomorphism is the alternating group
  $ ker("sgn") = A_n. $
]

== Symmetry

=== In Metric Spaces

#definition[Isometry][
  Let $(X, d_X)$ and $(Y, d_Y)$ be metric spaces.
  A map $f : X -> Y$ is an *isometry* if
  it perserves distances, i.e.,
  $ d_X (x_1, x_2) = d_Y (f(x_1), f(x_2)) quad forall x_1, x_2 in X. $
]

#definition[Symmetry][
  A *symmetry* of an object $O subset.eq X$ in a metric space $(X, d)$ is
  an isometry $f : X -> X$ with the image $f(O) = O$.

  Informally, a symmetry of a geometric object is
  a rearrangment of the object preserving
  the arrangement of its sides and vertices
  as well as its distances and angles.
]

#examples[
  Some types of symmetries:

  + / Reflectional:
      Reflection across a hyperplane
      (a line in $RR^2$ or a plane in $RR^3$)
  + / Rotational:
      Rotation within a plane
      ($RR^2$ is rotated around a fixed point, while
      $RR^3$ is rotated around an axis).
  + / Translational:
      All points are shifted by a constant vector.
  + / Identity:
      No change.
]

// Im unsure of the following
#definition[Rigid Motion][
  A *rigid motion* is a map $f : RR^n -> RR^n$ such that
  $ norm(u - v) = norm(f(u) - f(v)) quad forall u, v in RR^n. $

  Equivalently, it is a surjective isometry between Euclidean spaces
]

#example[
  A symmetry of an object in an Euclidean space $X = RR^n$
  is also a rigid motion.
]

=== Dihedral Groups

#definition[Dihedral Group][
  The *dihedral group* $D_n$ or $D_(2 n)$ is
  the group of symmetries (or equivalently rigid motions) of an $n$-gon.
  Its degree is $n$ and its order is $2n$.
]

#theorem[
  The dihedral group can be represented as
  $ D_n = ⟨r, s mid(|) r^n = s^2 = 1, r s = s r^(-1)⟩. $
]

= Rings

== Definition

#definition[Ring][
  A *ring* is a set $R$ with two binary operations $+$ and $dot$ such that
  + $(R, +)$ is an abelian group with identity $0$.
  + $(R, dot)$ is a monoid with identity $1$.
  + Multiplication distributes over addition:\
    for all $a, b, c in R$, $a dot (b + c) = a dot b + a dot c$.
]

#definition[Group of Units][
  Let $(R, +, dot)$ be a ring.
  The *group of units* $U(R)$ is the set of all elements in $R$ that have
  multiplicative inverses, i.e.,
  $
    U(R) =
    {a in R mid(|) exists a^(-1) in R : a dot a^(-1) = a^(-1) dot a = 1}.
  $
]

= Fields

== Definition

#definition[Field][
  A *field* is a set $F$
  with two binary operations $+$ and $dot$ such that
  + $(F, +)$ is an abelian group with identity $0$.
  + $(F\\{0}, dot)$ is an abelian group with identity $1$.
  + Multiplication distributes over addition:\
    for all $a, b, c in F$, $a dot (b + c) = a dot b + a dot c$.
]


#examples[
  $QQ, RR, CC, RR(x), QQ(i),$ and $FF_p$ for prime $p$.
]

== Vector Spaces

#definition[Vector Space][
  A vector space over a field $F$ is a set $V$ with two operations:
  - Vector addition $+ : V times V -> V$
  - Scalar multiplication $dot : F times V -> V$

  These must satisfy
  + (Closure under addition)
    $ve(u) + ve(v) in V$
  + (Distributivity over vectors)
    $a (ve(u) + ve(v)) = a ve(u) + a ve(v)$
  + (Associativity)
    $ve(u) + (ve(v) + ve(w)) = (ve(u) + ve(v)) + ve(w)$
  + (Identity)
    $ve(u) + ve(0) = ve(u)$
    \ \
  + (Inverse)
    $ve(u) + (-ve(u)) = ve(0)$
  + (Commutativity)
    $ve(u) + ve(v) = ve(v) + ve(u)$
    \ \
  + (Closure under scalar multiplication)
    $a ve(u) in V$
  + (Distributivity over scalars)
    $(a + b) ve(u) = a ve(u) + b ve(u)$
  + (Associativity)
    $a (b ve(u)) = (a b) ve(u)$
  + (Identity)
    $1 ve(u) = ve(u)$

  Note that requiring closure is often omitted.
]
